// Generated by duke-types from Address.java
// Do not edit manually.

export interface Address {
  street: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  apartment?: string;
  mapUri?: string;
}
