// Generated by duke-types from AuditLog.java
// Do not edit manually.

import type { Status } from './Status';

export interface AuditLog {
  id: string;
  eventCount: number;
  lastEventMillis: number;
  locked: boolean;
  currentStatus: Status;
  changedFields: string[];
  beforeSnapshot: Record<string, string>;
  afterSnapshot: Record<string, string>;
  tagsByCategory: Record<string, string[]>;
  observers: string[];
  scoreboard: Record<string, number>;
  latestChange: [string, string];
  topContributor?: [string, string, number];
}
