// Generated by duke-types from MediaAttachment.java
// Do not edit manually.

export interface MediaAttachment {
  id: string;
  filename: string;
  sizeBytes: number;
  storageUri: string;
  downloadUrl: string;
  localCachePath?: string;
  tempFile?: string;
  mimePattern: string;
  checksum: string;
  metadata?: any;
  properties?: Record<string, any>;
  tags?: any[];
  uploadedAt: string;
}
