// Generated by duke-types from User.java
// Do not edit manually.

import type { Address } from './Address';
import type { BaseEntity } from './BaseEntity';
import type { Role } from './Role';
import type { Status } from './Status';

export interface User extends BaseEntity {
  id: string;
  firstName: string;
  lastName: string;
  middleName?: string;
  email: string;
  address?: Address;
  roles: Role[];
  status: Status;
  preferences: Record<string, string>;
  locale: string;
  currency: string;
  avatar?: string;
  metadata?: any;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string;
}
